spring:
  application:
    name: springcloud-eureka-server
server:
  port: 8001

eureka:
  instance:
    hostname: eureka1 #hostname用于eureka集群服务器之间的区分
    lease-expiration-duration-in-seconds: 90 #最后一次心跳后，间隔多久认定微服务不可用，默认90
  client:
    register-with-eureka: false #不向自身注册。由于该应用为单个注册中心，所以设置为false，代表不向注册中心注册自己。
    fetch-registry: false #不从自身拉取注册信息。由于单个注册中心，不拉取自身信息。
    service-url:  # eureka server 的地址， 咱们单实例模式就写自己好了
      defaultZone: http://localhost:8001/eureka/
  server:
    enable-self-preservation: false #eureka的自我保护状态。测试时将其关闭